name: Reproducible pipeline

on:
  push:
    branches:
      - main
      - master

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t housing_image .
    - name: Docker Run Action
      run: docker run --rm --name housing_container -v /github/workspace/shared_folder:/home/housing/shared_folder:rw housing_image

    - name: Create the runs branch if it does not already exist
      if: steps.runs-exist.outcome != 'success'
      run: git checkout --orphan rap-run

    - name: Upload latest run
      run: |
        git config --local user.name "GitHub Actions"
        git config --local user.email "actions@github.com"
        git add /github/workspace/shared_folder/
        git commit -am "Run pipeline"
        git push origin rap-run
