name: Reproducible pipeline

on:
  push:
    branches:
      - main
      - master

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: rap-runs
        fetch-depth: 1
        path: .rap-runs
        
    - name: Build the Docker image
      run: docker build -t housing_image .
    - name: Docker Run Action
      run: docker run --rm --name housing_container -v $(pwd)/shared_folder:/home/housing/shared_folder:rw housing_image
      working-directory: .

    - name: Upload latest run
      run: |
        git config --local user.name "GitHub Actions"
        git config --local user.email "actions@github.com"
        git add $(pwd)/shared_folder/
        git commit -am "Run pipeline"
        git push origin rap-run
